name: VisualizeBinaryTrees
channels:
- pytorch
- anaconda
- defaults
dependencies:
- python=3.7.*
- numpy
- pickle
- logging
- matplotlib
- importlib
- itertools
- sys
#- h5py
#- scipy=1.0.*
#- scikit-learn=0.19.*
#- six
#- pytorch=0.4.*
#- pytest
- pip
- pip:
#  - uproot
#  - scikit-hep